### ISSUE TITLE
Tracker for modding dedicated server

### ISSUE THREAD

**Issue by ZXMushroom63** [eaglerforge/EaglerForge#35]
### by requesting a bug you must check these boxes

- [X] I have explained about the bug(s)
- [X] I have left attachments or code lines
- [X] I know that I won't waste your time
- [ ] I just checked all of these boxes without reading the labels

### about the bug

This is a tracker for modding the single player dedicated server. Currently, all mods run client-side, even in single player. Exposing the dedicated server is probably going to be hard due to it running in it's own sandboxed web worker (no exposing instances).

Current best idea from me is add a custom packet that you can send to a server that runs a `new Function()` in the web worker's context. Then, you can use the Web BroadcastChannel API to exchange information backwards and forwards between client and dedicated server.

Additionally, to make use of the already existing ModAPI, using `globalThis` rather than `window`. (web workers do not have a window)

**Comment by STPv22** [comment]
V1.4 (i assume) is going to be fire

**Comment by ZXMushroom63** [comment]
> V1.4 (i assume) is going to be fire

if i get this working

**Comment by STPv22** [comment]
> > V1.4 (i assume) is going to be fire
> 
> if i get this working
Theres still the java gui if it doesn't

**Comment by OeildeLynx31** [comment]
You could try beginning with a packet to send to the server which can execute a cheat command as player, so we can summon mobs and place blocks

**Comment by ZXMushroom63** [comment]
Posting an update here: I successfully hooked into the dedicated server, meaning that you can now mod it when the new release comes out

**Comment by STPv22** [comment]
NOICE

**Comment by STPv22** [comment]
Wait, what does this allow is to do?

**Comment by OeildeLynx31** [comment]
> Wait, what does this allow is to do?

Everything you can do with a basic mod, which isn't adding new mobs or blocks. You can edit as you want, but I don't think you can make new ones.

**Comment by STPv22** [comment]
> > Wait, what does this allow is to do?
> 
> Everything you can do with a basic mod, which isn't adding new mobs or blocks. You can edit as you want, but I don't think you can make new ones.

?

**Comment by ZXMushroom63** [comment]
> > Wait, what does this allow is to do?
> 
> Everything you can do with a basic mod, which isn't adding new mobs or blocks. You can edit as you want, but I don't think you can make new ones.

you can definetely add new items, just in a non traditional way. You would have items differentiated via lore tags or similar, and then modify the client side renderer and add custom behaviours server side.

**Comment by STPv22** [comment]
Nice huh

**Comment by OeildeLynx31** [comment]
> > > Wait, what does this allow is to do?
> > 
> > Everything you can do with a basic mod, which isn't adding new mobs or blocks. You can edit as you want, but I don't think you can make new ones.
> 
> you can definetely add new items, just in a non traditional way. You would have items differentiated via lore tags or similar, and then modify the client side renderer and add custom behaviours server side.

Could you make an example mod of this?

**Comment by ZXMushroom63** [comment]
> > > > Wait, what does this allow is to do?
> > > 
> > > 
> > > Everything you can do with a basic mod, which isn't adding new mobs or blocks. You can edit as you want, but I don't think you can make new ones.
> > 
> > 
> > you can definetely add new items, just in a non traditional way. You would have items differentiated via lore tags or similar, and then modify the client side renderer and add custom behaviours server side.
> 
> Could you make an example mod of this?

eventually
